### ISSUE TITLE
Issues with env vars containing $

### ISSUE THREAD

**Issue by sbidoul** [acsone/odoo-bedrock-k8s-deployer#3]
We had an example with a password starting with a $ that ended up empty in the deployment yaml.

**Comment by qgroulard** [comment]
This issue comes from GitLab. Variables with '$' are not correctly set, see [this issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/45173).
A workaround is to double the '$'.

**Comment by sbidoul** [comment]
Ok, thanks for the investigation. The workaround looks good to me.
